# Generated by Django 3.1.7 on 2021-04-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='academic',
            field=models.CharField(choices=[('1', '1st year'), ('2', '2nd year'), ('3', '3rd year'), ('4', '4t year')], max_length=20),
        ),
        migrations.AlterField(
            model_name='depart',
            name='year',
            field=models.CharField(choices=[('1', '1st year'), ('2', '2nd year'), ('3', '3rd year'), ('4', '4t year')], max_length=20, unique=True),
        ),
    ]
