# Generated by Django 3.1.7 on 2021-04-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20210408_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='depart',
            name='name',
            field=models.CharField(default=1.0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
